spring:
  application:
    name: vhttest
  redis:
    redisson:
      config: |
        singleServerConfig:
          address: redis://springcache:6379
          password:
          database: 0

  datasource:
    url: jdbc:mysql://springdb:3306/test?useSSL=false
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: none
      show-sql: false
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
server:
  port: 6075
