spring:
  application:
    name: vhttest
  redis:
    redisson:
      config: |
        singleServerConfig:
          address: redis://localhost:6377
          password:
          database: 0
# or config redis sentinel
#spring:
#  redis:
#    redisson:
#      config: |
#        sentinelServersConfig:
#          masterName: mymaster
#          sentinelAddresses:
#            - redis://127.0.0.1:26379
#            - redis://127.0.0.1:26380
#            - redis://127.0.0.1:26381
#          password: yourpassword
#          database: 0
#          timeout: 3000
#          connectTimeout: 10000
#          retryAttempts: 3
#          retryInterval: 1500
#          subscriptionsPerConnection: 5
#          subscriptionConnectionMinimumIdleSize: 1
#          subscriptionConnectionPoolSize: 50
#          slaveConnectionMinimumIdleSize: 10
#          slaveConnectionPoolSize: 64
#          masterConnectionMinimumIdleSize: 10
#          masterConnectionPoolSize: 64
#          idleConnectionTimeout: 10000
#          pingTimeout: 1000
#          keepAlive: true
#          tcpNoDelay: true
#          dnsMonitoringInterval: 5000
  datasource:
    url: jdbc:mysql://127.0.0.1:3309/test?useSSL=false
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
server:
  port: 6075
